---
# System Setup Handlers

- name: restart ntp
  systemd:
    name: ntp
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload sysctl
  sysctl:
    state: reloaded
