---
# Static Files Setup

- name: Collect static files
  command: "{{ virtualenv_path }}/bin/python -c 'import os; os.system(\"python -m app.static\")'"
  args:
    chdir: "{{ airpuff_app_home }}/backend"
  become_user: "{{ airpuff_app_user }}"
  tags: [app, static]

- name: Set static files permissions
  file:
    path: "{{ airpuff_app_home }}/backend/app/static"
    state: directory
    owner: "{{ airpuff_app_user }}"
    group: "{{ airpuff_app_group }}"
    mode: '0755'
    recurse: yes
  tags: [app, static]
